### ISSUE TITLE
Specify Multithreading.

### ISSUE THREAD

**Issue by miketweaver** [johnno1962/mtar#1]
I'm really impressed with mtar so far. I've used it a lot and it's perfect for what I need. Tar-ing and compressing terabytes of information almost has to be multithreaded. 

One issue I have is that I would like to specify the number of threads to actually use.
Pigz has the flag -p that does exactly that. Is there any way you can implement the same?

**Comment by johnno1962** [comment]
Hi, I’ve added this as an option to the threaded compressor. Use —option threads=NN after the archive filename. You’ll need to build your own version as I’ve not updated the the binaries as yet.

**Comment by miketweaver** [comment]
Thanks for this! That was fast.

We'll build this today and I'll let you know if anything goes wrong.

**Comment by svennd** [comment]
Just for reference its really ment as --option for example : 
`mtar czfY my_archive.tar.gz --option threads=2 my_dir/`

Thanks for this tool !
